version: "3.7"

services:
  broker-service:
    container_name: broker-service
    build:
      context: ./broker-service
    ports:
      - 8080:8080
    restart: always
    deploy:
      replicas: 1
  todo-service:
    depends_on:
      - mongodb
    container_name: todo-service
    build:
      context: ./todo-service
    ports:
      - 8081:8081
    restart: always
    deploy:
      replicas: 1
  mongodb:
    image: mongo:4.2.8
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
volumes:
  mongo-db:
